backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

local_backend: true

i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, de]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog/"
    create: true
    i18n: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post", i18n: duplicate}
      - {label: "Title", name: "title", widget: "string", i18n: true}
      - {label: "Publish Date", name: "date", widget: "datetime", i18n: duplicate}
      - {label: "Description", name: "description", widget: "text", i18n: true}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean", i18n: duplicate}
      - {label: "Featured Image", name: "featuredimage", widget: image, i18n: duplicate}
      - {label: "Body", name: "body", widget: "markdown", i18n: true}
      - {label: "Tags", name: "tags", widget: "list", i18n: true}

  - name: "pages"
    label: "Pages"
    i18n: true
      structure: single_file
      locales: [en, de]
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        i18n: true
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page", i18n: duplicate}
          - {label: Title, name: title, widget: string, i18n: true}
          - {label: Image, name: image, widget: image, i18n: true}
          - {label: Heading, name: heading, widget: string, i18n: true}
          - {label: Subheading, name: subheading, widget: string, i18n: true}
          - {label: Mainpitch, name: mainpitch, widget: object, i18n: true, fields: [{label: Title, name: title, widget: string}, {label: Description, name: description, widget: text}]}
          - {label: Description, name: description, widget: string, i18n: true}
          - {label: Intro, name: intro, widget: object, i18n: true, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, i18n: true, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        i18n: true
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page", i18n: duplicate}
          - {label: "Title", name: "title", widget: "string", i18n: true}
          - {label: "Body", name: "body", widget: "markdown", i18n: true}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        i18n: true
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page", i18n: duplicate}
          - {label: Title, name: title, widget: string, i18n: true}
          - {label: Image, name: image, widget: image, i18n: true}
          - {label: Heading, name: heading, widget: string, i18n: true}
          - {label: Description, name: description, widget: string, i18n: true}
          - {label: Intro, name: intro, widget: object, i18n: true, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, i18n: true, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, i18n: true, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image, i18n: true}
          - {label: Pricing, name: pricing, widget: object, i18n: true, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
